RAW_FOLDER = '__RAW'
SOURCE_FOLDER = '__SOURCE'
TOKEN_FOLDER = '__CONTEXT'
SCHEMA_FOLDER = '__SCHEMAS'
SCHEMA_DIRPATH = 'schema_dirpath'

SCHEMA_NAME = "__SCHEMA"
CONTENT = "__CONTENT"

ENV_FILTERS = "__FILTERS"
ENV_FUNCTIONS = "__FUNCTIONS"

ERROR_ON_MISSING_CONTEXT = False